#!/usr/bin/env sh
output='maryknoll.txt'

for c in {A..Z}; do
	if [ ! -f "src/${c}-html.html" ]; then
		echo "Converting ${c}.pdf to html..."
		pdftohtml -c -s "src/${c}.pdf" > /dev/null
	fi
done

echo 'Converting html to text...'
./html_to_txt > "${output}" && patch "${output}" 'tweaks.patch'
